import { useEffect, useState } from "react";
import api from "../api";
import PageHeader from "../components/PageHeader";
import { alertaErro, alertaSucesso } from "../utils/alerts";

const inicial={produtoId:"",lote:"",validade:"",fornecedor:"",custoUnitario:0,quantidade:1};
export default function EstoqueLotes(){
 const [lista,setLista]=useState([]),[produtos,setProdutos]=useState([]),[form,setForm]=useState(inicial);
 async function carregar(){try{const [l,p]=await Promise.all([api.get("/produto-lotes"),api.get("/produtos")]);setLista(l.data||[]);setProdutos(p.data||[]);}catch{alertaErro("Erro ao carregar lotes.");}}
 async function salvar(e){e.preventDefault();await api.post("/produto-lotes",{...form,produtoId:Number(form.produtoId),quantidade:Number(form.quantidade),custoUnitario:Number(form.custoUnitario),validade:form.validade||null});setForm(inicial);await carregar();alertaSucesso("Lote salvo.");}
 async function baixar(id){const qtd=window.prompt("Quantidade para baixa/uso interno:"); if(!qtd)return; await api.post(`/produto-lotes/${id}/baixar`,{quantidade:Number(qtd),observacao:"Baixa manual por uso interno"}); await carregar(); alertaSucesso("Baixa registrada.");}
 useEffect(()=>{carregar();},[]);
 return <div><PageHeader title="Lotes e Validades" subtitle="Controle clínico de lote, vencimento, fornecedor, custo e alerta visual" /><form className="panel mb-3" onSubmit={salvar}><div className="row g-2"><div className="col-md-3"><label>Produto</label><select className="form-select" value={form.produtoId} onChange={e=>setForm({...form,produtoId:e.target.value})} required><option value="">Selecione...</option>{produtos.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></div><div className="col-md-2"><label>Lote</label><input className="form-control" value={form.lote} onChange={e=>setForm({...form,lote:e.target.value})}/></div><div className="col-md-2"><label>Validade</label><input type="date" className="form-control" value={form.validade} onChange={e=>setForm({...form,validade:e.target.value})}/></div><div className="col-md-2"><label>Fornecedor</label><input className="form-control" value={form.fornecedor} onChange={e=>setForm({...form,fornecedor:e.target.value})}/></div><div className="col-md-1"><label>Qtd</label><input type="number" step="0.001" className="form-control" value={form.quantidade} onChange={e=>setForm({...form,quantidade:e.target.value})}/></div><div className="col-md-1"><label>Custo</label><input type="number" step="0.01" className="form-control" value={form.custoUnitario} onChange={e=>setForm({...form,custoUnitario:e.target.value})}/></div><div className="col-md-1 d-flex align-items-end"><button className="btn btn-primary w-100">Salvar</button></div></div></form><div className="panel"><table className="table professional-table"><thead><tr><th>Produto</th><th>Lote</th><th>Validade</th><th>Fornecedor</th><th>Qtd</th><th>Ações</th></tr></thead><tbody>{lista.map(x=>{const vencendo=x.validade&&new Date(x.validade)<new Date(Date.now()+1000*60*60*24*30);return <tr key={x.id} className={vencendo?"table-warning":""}><td>{x.produto?.nome}</td><td>{x.lote}</td><td>{x.validade?new Date(x.validade).toLocaleDateString("pt-BR"):"-"}</td><td>{x.fornecedor}</td><td>{x.quantidade}</td><td><button className="btn btn-outline-danger btn-sm" onClick={()=>baixar(x.id)}>Baixar</button></td></tr>})}</tbody></table></div></div>
}
